builds:
	- hooks:
		post: ./postrelease.sh
	- binary: gthsmanage
	- main: main.go
	- goos:
      - windows
      - darwin
      - linux
	- goarch:
      - amd64

archive:
	format: zip
	replacements:
		amd64: x64
		darwin: macOS
