project_name: gthsmanage
release:
  github:
    owner: willyb321
    name: gthsmanage
brew:
  github:
    owner: willyb321
    name: homebrew-brewing
  homepage: "https://github.com/willyb321/gthsmanage/"
  description: "Software to keep the GTHS Noticeboard running."
  install: |
    bin.install "gthsmanage"
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  main: main.go
  binary: gthsmanage
archive:
  replacements:
    amd64: x64
    darwin: macOS
  format: zip
