project_name: gthsManage
release:
  github:
    owner: willyb321
    name: gthsManage
brew:
  github:
    owner: willyb321
    name: brewing
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  main: main.go
  binary: gthsManage
archive:
  replacements:
    amd64: x64
    darwin: macOS
  format: zip
